### ISSUE TITLE
Error au déploiement sur heroku

### ISSUE THREAD

**Issue by seblm** [xebia-france/xwhois#21]
```
$ heroku login
$ heroku create xwhois
$ git push heroku master
Counting objects: 1339, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (1113/1113), done.
Writing objects: 100% (1339/1339), 2.01 MiB | 38.00 KiB/s, done.
Total 1339 (delta 646), reused 396 (delta 174)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Reading application state
remote:        package.json...
remote:        build directory...
remote:        cache directory...
remote:        environment variables...
remote:
remote:        Node engine:         unspecified
remote:        Npm engine:          unspecified
remote:        Start mechanism:     npm start
remote:        node_modules source: package.json
remote:        node_modules cached: false
remote:
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        Resolving node version (latest stable) via semver.io...
remote:        Downloading and installing node 0.12.4...
remote:        Using default npm version: 2.10.1
remote:
remote: -----> Building dependencies
remote:        Installing node modules
remote:        npm WARN package.json xwhois@1.0.0 No license field.
remote:
remote:        > kerberos@0.0.12 install /tmp/build_0b86815b92e9ad1bac9619a86e8c0498/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
remote:        > (node-gyp rebuild 2> builderror.log) || (exit 0)
remote:
remote:        make: Entering directory `/tmp/build_0b86815b92e9ad1bac9619a86e8c0498/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
remote:          CXX(target) Release/obj.target/kerberos/lib/kerberos.o
remote:          CXX(target) Release/obj.target/kerberos/lib/worker.o
remote:          CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
remote:          CC(target) Release/obj.target/kerberos/lib/base64.o
remote:          CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
remote:          SOLINK_MODULE(target) Release/obj.target/kerberos.node
remote:          SOLINK_MODULE(target) Release/obj.target/kerberos.node: Finished
remote:          COPY Release/kerberos.node
remote:        make: Leaving directory `/tmp/build_0b86815b92e9ad1bac9619a86e8c0498/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
remote:        npm WARN installMany nopt was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany npmlog was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany request was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany semver was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany tar was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany tar-pack was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany mkdirp was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany rc was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany rimraf was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:
remote:        > bson-ext@0.1.7 install /tmp/build_0b86815b92e9ad1bac9619a86e8c0498/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext
remote:        > (node-pre-gyp install --fallback-to-build) || (node-gyp rebuild 2> builderror.log) || (exit 0)
remote:
remote:        make: Entering directory `/tmp/build_0b86815b92e9ad1bac9619a86e8c0498/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
remote:          CXX(target) Release/obj.target/bson/ext/bson.o
remote:          SOLINK_MODULE(target) Release/obj.target/bson.node
remote:          SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
remote:          COPY Release/bson.node
remote:        make: Leaving directory `/tmp/build_0b86815b92e9ad1bac9619a86e8c0498/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
remote:
remote:        > xwhois@1.0.0 install /tmp/build_0b86815b92e9ad1bac9619a86e8c0498
remote:        > bower install
remote:
remote:        sh: 1: bower: not found
remote:
remote:        npm ERR! Linux 3.13.0-49-generic
remote:        npm ERR! argv "/tmp/build_0b86815b92e9ad1bac9619a86e8c0498/.heroku/node/bin/node" "/tmp/build_0b86815b92e9ad1bac9619a86e8c0498/.heroku/node/bin/npm" "install" "--unsafe-perm" "--quiet" "--userconfig" "/tmp/build_0b86815b92e9ad1bac9619a86e8c0498/.npmrc"
remote:        npm ERR! node v0.12.4
remote:        npm ERR! npm  v2.10.1
remote:        npm ERR! file sh
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno ENOENT
remote:        npm ERR! syscall spawn
remote:        npm ERR! xwhois@1.0.0 install: `bower install`
remote:        npm ERR! spawn ENOENT
remote:        npm ERR!
remote:        npm ERR! Failed at the xwhois@1.0.0 install script 'bower install'.
remote:        npm ERR! This is most likely a problem with the xwhois package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     bower install
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls xwhois
remote:        npm ERR! There is likely additional logging output above.
remote:
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_0b86815b92e9ad1bac9619a86e8c0498/npm-debug.log
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing!
remote:
remote:        Are you running into a common issue?
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        During the build we spotted some likely problems:
remote:
remote:        - Node version not specified in package.json
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app
remote:
remote: Verifying deploy....
remote:
remote: !   Push rejected to xwhois.
remote:
To https://git.heroku.com/xwhois.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/xwhois.git'
```

**Comment by alexandrehebert** [comment]
Deux options : 
- Heroku n'aime pas le fait d'avoir surchargé "npm start" et "npm install"
- On a oublié de préciser que bower est une dépendance globale quelque part

**Comment by alexandrehebert** [comment]
Problem solved !

> remote: -----> Discovering process types
> remote:        Procfile declares types   -> (none)
> remote:        Default types for Node.js -> web
> remote: 
> remote: -----> Compressing... done, 19.7MB
> remote: -----> Launching... done, v3
> remote:        https://xwhois-ahebert.herokuapp.com/ deployed to Heroku
> remote: 
> remote: Verifying deploy... done.
> To https://git.heroku.com/xwhois-ahebert.git
> - [new branch]      master -> master

**Comment by alexandrehebert** [comment]
En revanche, l'application déployée ne fonctionne pas, surement pour d'autres raisons.

**Comment by seblm** [comment]
```
$ rm -fr node_modules/ build/
$ npm install
$ gulp
$ CONFLUENCE=true CONFLUENCE_HOSTNAME=intranet.xebia.com CONFLUENCE_USER=$1 CONFLUENCE_PASSWORD="$(cat pass.txt)" CONFLUENCE_RESOURCE_ID=4522409 node server.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/seb/src/xebia-france/xwhois/src/api/infrastructure/trombinoscopeDb.js:1:71)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Le commit 3091fd9 a supprimé la dépendance à `q`.

**Comment by seblm** [comment]
Corrigé avec [ce commit](https://github.com/xebia-france/xwhois/commit/a175a510168cea8440f967c76c73f2045cb2c563).

**Comment by seblm** [comment]
Nouvelle erreur :

```
fs.js:0
 (function (exports, require, module, __filename, __dirname) { // Copyright Joy

Error: ENOENT, no such file or directory '/app/build/favicon.ico'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at favicon (/app/node_modules/serve-favicon/index.js:64:15)
    at Object.<anonymous> (/app/server.js:28:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at startup (node.js:129:16)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by seblm** [comment]
Au vu de toutes ces erreurs j'ai plutôt envie de builder sur une autre machine qu'heroku.

**Comment by alexandrehebert** [comment]
Ah oui effectivement, Heroku nous imposait pas mal de configurations particulières.
Finalement on est donc full AWS ? Notre "prod" va nous servir d'intégration aussi ?

**Comment by seblm** [comment]
Pour l'instant l'autre machine, c'est ton poste de dev qui bugfix/21-deploiement puis sur heroku/master.
On a une machine dans AWS pour mongodb.
Il nous faudrait une pré-prod heroku (genre xwhois-preprod.herokuapp.com) et un autre schéma de base mongo pour la pré-prod (mais qui taperai sur le même serveur AWS).
